markdown: redcarpet
redcarpet:
    extensions: ["tables"]
permalink: /:title/
url: http://liangbizhi.github.io
name: liangbizhi
author: liangbizhi
email: liangbizhi1993#gmail.com（把#号换成@）
duoshuo: liangbizhi
weibo: 1037054042
appkey: 3989909957
github: liangbizhi
highlighter: pygments
safe: true
paginate: 20
